import {esc,wait} from './shared.js?v=20260922-showroom3';
const steps=['Nova linha detectada','Validando dados','Dados válidos ✓','Apps Script executando','Pedido processado','Relatório atualizado','Notificação enviada ✓'];
let rootRef=null,running=false,active=-1,guideText='',guideToken=0;
const logs=()=>{const l=['18:31:02 Entrada detectada','18:31:02 Validando registro','18:31:03 Dados válidos','18:31:03 Processamento iniciado','18:31:03 Dashboard atualizado','18:31:04 Relatório atualizado','18:31:04 Processo concluído'];return l.slice(0,Math.max(1,active+1)).map((x,i)=>i===active?'<b>'+x+'</b>':x).join('<br>')};
const done=()=>active>=steps.length-1;
const render=()=>{if(!rootRef)return;rootRef.innerHTML=`<div class="miniapp"><div class="miniapp-shell">${guideText?'<div class="demo-guide-banner"><strong>DEMONSTRAÇÃO GUIADA</strong><span>'+esc(guideText)+'</span></div>':''}<div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Automação / Apps Script<small class="miniapp-muted">Planilha iniciando uma operação completa</small></div></div><button class="mini-btn primary" id="auto-run" ${running?'disabled':''}>${running?'Executando…':'Executar automação'}</button></div>
<div class="demo-challenge ${done()?'completed':''}"><small>DESAFIO</small><strong>${done()?'✓ DESAFIO CONCLUÍDO':'Execute o processamento do pedido.'}</strong><p>${done()?'Você transformou uma linha de planilha em processamento, dashboard e notificação.':'Clique em Executar automação e acompanhe cada etapa.'}</p></div>
<div class="mini-grid-2"><div class="mini-panel"><strong>Planilha de entrada</strong><table class="mini-table" style="margin-top:8px"><thead><tr><th>Pedido</th><th>Cliente</th><th>Volumes</th><th>Status</th></tr></thead><tbody><tr><td>PED-8841</td><td>Mercado Horizonte</td><td>8</td><td><span class="mini-status ${done()?'ok':'warn'}">${done()?'Processado':'Pendente'}</span></td></tr></tbody></table><div class="flow-track" style="margin-top:12px">${steps.map((s,i)=>`<div class="flow-node ${i<active?'done':i===active?'active':''}"><span>0${i+1}</span><br>${s}</div>`).join('')}</div></div><div><div class="mini-log">${logs()}</div><p class="miniapp-muted">PLANILHA NÃO PRECISA SER APENAS PLANILHA. Ela pode iniciar uma operação completa.</p></div></div></div></div>`;document.getElementById('auto-run')?.addEventListener('click',()=>run(false))};
const run=async(fromGuide=false)=>{if(running)return;running=true;active=-1;render();const token=++guideToken;for(let i=0;i<steps.length;i++){if(token!==guideToken)return;active=i;if(fromGuide)guideText=steps[i];render();await wait(620)}running=false;render()};
const reset=()=>{guideToken++;running=false;active=-1;guideText='';render()};
const guide=async()=>{reset();guideText='Uma nova linha acabou de entrar na planilha.';render();await wait(800);return run(true)};
export async function mount(root){rootRef=root;render();return{reset,guide,cancelGuide(){guideToken++;running=false},destroy(){guideToken++;rootRef=null}}}
