import {clone,barChart,wait,esc} from './shared.js?v=20260922-showroom4';
const initial=[
{period:'Hoje',status:'Entregue',category:'Logística',value:42,revenue:12800},
{period:'Hoje',status:'Pendente',category:'Logística',value:7,revenue:2100},
{period:'7 dias',status:'Entregue',category:'Operação',value:164,revenue:49800},
{period:'7 dias',status:'Em rota',category:'Logística',value:36,revenue:11200},
{period:'30 dias',status:'Entregue',category:'Operação',value:612,revenue:182000},
{period:'30 dias',status:'Pendente',category:'Comercial',value:28,revenue:9400}
];let data=clone(initial),rootRef=null,p='Todos',s='Todos',c='Todos',metrics={orders:127,otif:94.1,pending:8,deliveries:119},processed=false,guideText='',guideToken=0;
const render=()=>{const f=data.filter(x=>(p==='Todos'||x.period===p)&&(s==='Todos'||x.status===s)&&(c==='Todos'||x.category===c));rootRef.innerHTML=`<div class="miniapp"><div class="miniapp-shell">${guideText?'<div class="demo-guide-banner"><strong>DEMONSTRAÇÃO GUIADA</strong><span>'+esc(guideText)+'</span></div>':''}<div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Dashboard Executivo<small class="miniapp-muted">Indicadores reativos</small></div></div><div class="miniapp-actions"><span class="mini-status ok">● Atualizado agora</span><button class="mini-btn primary" id="dash-process">Processar pedido</button></div></div>
<div class="demo-challenge ${processed?'completed':''}"><small>DESAFIO</small><strong>${processed?'✓ DESAFIO CONCLUÍDO':'Processe um pedido e observe os indicadores.'}</strong><p>${processed?'Pedidos, pendências, OTIF e gráfico reagiram à mesma ação.':'Clique em Processar pedido e veja a causa do número mudar.'}</p></div>
<div class="mini-panel"><div class="miniapp-toolbar">${select('dash-p',['Todos','Hoje','7 dias','30 dias'],p)}${select('dash-s',['Todos','Entregue','Pendente','Em rota'],s)}${select('dash-c',['Todos','Logística','Operação','Comercial'],c)}</div></div>
<div class="mini-kpis"><div class="mini-kpi"><small>Pedidos</small><strong>${metrics.orders}</strong></div><div class="mini-kpi ok"><small>OTIF</small><strong>${metrics.otif.toFixed(1).replace('.',',')}%</strong></div><div class="mini-kpi warn"><small>Pendências</small><strong>${metrics.pending}</strong></div><div class="mini-kpi ok"><small>Entregas</small><strong>${metrics.deliveries}</strong></div></div>
<div class="mini-grid-2"><div class="mini-panel"><strong>Volume por status</strong>${barChart(['Entregue','Em rota','Pendente'].map(st=>({label:st.split(' ')[0],value:f.filter(x=>x.status===st).reduce((a,x)=>a+x.value,0)+(processed&&st==='Entregue'?18:0)})))}</div><div class="mini-panel"><strong>Leitura executiva</strong><div style="margin-top:14px">${f.map(x=>`<div class="route-line"><span class="route-num">${x.value}</span><div><strong>${x.status}</strong><div class="miniapp-muted">${x.period} · ${x.category}</div></div><span>R$ ${Math.round(x.revenue/1000)}k</span></div>`).join('')||'<div class="mini-empty">Sem dados para estes filtros.</div>'}</div></div></div></div></div>`;bind()};
const select=(id,opts,val)=>`<select class="mini-select" id="${id}">${opts.map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('')}</select>`;
const processOrder=()=>{if(processed)return;processed=true;metrics={orders:128,otif:94.3,pending:7,deliveries:120};render()};
const bind=()=>{[['dash-p','p'],['dash-s','s'],['dash-c','c']].forEach(([id,k])=>document.getElementById(id)?.addEventListener('change',e=>{if(k==='p')p=e.target.value;if(k==='s')s=e.target.value;if(k==='c')c=e.target.value;render()}));document.getElementById('dash-process')?.addEventListener('click',processOrder)};
const reset=()=>{guideToken++;data=clone(initial);p=s=c='Todos';metrics={orders:127,otif:94.1,pending:8,deliveries:119};processed=false;guideText='';render()};
const guide=async()=>{reset();const token=++guideToken;guideText='Pedido PED-8841 foi concluído na operação.';render();await wait(1000);if(token!==guideToken)return;guideText='Atualizando indicadores executivos.';processOrder();await wait(1300);if(token!==guideToken)return;guideText='Pedidos 127 → 128 · Pendências 8 → 7 · OTIF 94,1% → 94,3%.';render()};
export async function mount(root){rootRef=root;render();return{reset,guide,cancelGuide(){guideToken++},destroy(){guideToken++;rootRef=null}}}
