import {clone,barChart} from './shared.js';
const initial=[
{period:'Hoje',status:'Entregue',category:'Logística',value:42,revenue:12800},
{period:'Hoje',status:'Pendente',category:'Logística',value:7,revenue:2100},
{period:'7 dias',status:'Entregue',category:'Operação',value:164,revenue:49800},
{period:'7 dias',status:'Em rota',category:'Logística',value:36,revenue:11200},
{period:'30 dias',status:'Entregue',category:'Operação',value:612,revenue:182000},
{period:'30 dias',status:'Pendente',category:'Comercial',value:28,revenue:9400}
];let data=clone(initial),rootRef=null,p='Todos',s='Todos',c='Todos';
const render=()=>{const f=data.filter(x=>(p==='Todos'||x.period===p)&&(s==='Todos'||x.status===s)&&(c==='Todos'||x.category===c));const total=f.reduce((a,x)=>a+x.value,0),rev=f.reduce((a,x)=>a+x.revenue,0),done=f.filter(x=>x.status==='Entregue').reduce((a,x)=>a+x.value,0);rootRef.innerHTML=`<div class="miniapp"><div class="miniapp-shell"><div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Dashboard Executivo<small class="miniapp-muted">Indicadores reativos</small></div></div><span class="mini-status ok">Atualizado agora</span></div><div class="mini-panel"><div class="miniapp-toolbar">${select('dash-p',['Todos','Hoje','7 dias','30 dias'],p)}${select('dash-s',['Todos','Entregue','Pendente','Em rota'],s)}${select('dash-c',['Todos','Logística','Operação','Comercial'],c)}</div></div><div class="mini-kpis"><div class="mini-kpi"><small>Volume</small><strong>${total}</strong></div><div class="mini-kpi ok"><small>Concluídos</small><strong>${done}</strong></div><div class="mini-kpi"><small>Receita simulada</small><strong>R$ ${Math.round(rev/1000)}k</strong></div><div class="mini-kpi"><small>Registros filtrados</small><strong>${f.length}</strong></div></div><div class="mini-grid-2"><div class="mini-panel"><strong>Volume por status</strong>${barChart(['Entregue','Em rota','Pendente'].map(st=>({label:st.split(' ')[0],value:f.filter(x=>x.status===st).reduce((a,x)=>a+x.value,0)})))}</div><div class="mini-panel"><strong>Composição</strong><div style="margin-top:14px">${f.map(x=>`<div class="route-line"><span class="route-num">${x.value}</span><div><strong>${x.status}</strong><div class="miniapp-muted">${x.period} · ${x.category}</div></div><span>R$ ${Math.round(x.revenue/1000)}k</span></div>`).join('')||'<div class="mini-empty">Sem dados para estes filtros.</div>'}</div></div></div></div></div>`;bind()};
const select=(id,opts,val)=>`<select class="mini-select" id="${id}">${opts.map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('')}</select>`;
const bind=()=>{[['dash-p','p'],['dash-s','s'],['dash-c','c']].forEach(([id,k])=>document.getElementById(id)?.addEventListener('change',e=>{if(k==='p')p=e.target.value;if(k==='s')s=e.target.value;if(k==='c')c=e.target.value;render()}))};
export async function mount(root){rootRef=root;render();return{reset(){data=clone(initial);p=s=c='Todos';render()},destroy(){rootRef=null}}}
