import {clone,esc,statusClass,wait} from './shared.js';
const initial=[
{id:1,nf:'45821',client:'Mercado Horizonte',route:'Oeste 01',status:'Pendente',city:'Campo Grande',gps:false,proof:false},
{id:2,nf:'45834',client:'Drogaria Central',route:'Oeste 01',status:'Em rota',city:'Bangu',gps:true,proof:false},
{id:3,nf:'45851',client:'Casa Nova',route:'Sul 03',status:'Entregue',city:'Recreio',gps:true,proof:true},
{id:4,nf:'45872',client:'Rede Mais',route:'Oeste 02',status:'Pendente',city:'Santa Cruz',gps:false,proof:false}
];
let state=clone(initial),rootRef=null,q='',filter='Todos',openId=null,causeStep=0,guideText='',guideToken=0;
const challengeDone=()=>state.find(x=>x.nf==='45821')?.status==='Entregue';
const challenge=()=>`<div class="demo-challenge ${challengeDone()?'completed':''}"><small>DESAFIO</small><strong>${challengeDone()?'✓ DESAFIO CONCLUÍDO':'Finalize a NF 45821.'}</strong><p>${challengeDone()?'Status, comprovante e indicadores foram atualizados.':'Abra a entrega, capture GPS, inicie a rota, anexe comprovante e finalize.'}</p></div>`;
const cause=()=>`<div class="demo-cause-flow"><span class="${causeStep>=1?'done':''}">Iniciar rota</span><i>→</i><span class="${causeStep>=2?'done':''}">GPS</span><i>→</i><span class="${causeStep>=3?'done':''}">Comprovante</span><i>→</i><span class="${causeStep>=4?'done':''}">Entregue</span><i>→</i><span class="${causeStep>=5?'done':''}">KPI atualizado</span></div>`;
const render=()=>{const root=rootRef;if(!root)return;const list=state.filter(x=>(filter==='Todos'||x.status===filter)&&(!q||[x.nf,x.client,x.city].join(' ').toLowerCase().includes(q.toLowerCase())));const count=s=>state.filter(x=>x.status===s).length;
root.innerHTML=`<div class="miniapp"><div class="miniapp-shell">${guideText?'<div class="demo-guide-banner"><strong>DEMONSTRAÇÃO GUIADA</strong><span>'+esc(guideText)+'</span></div>':''}<div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Sistema de Entregas<small class="miniapp-muted">TMS demonstrativo</small></div></div><span class="mini-status ok">Operação online</span></div>
${challenge()}${cause()}<div class="mini-kpis"><div class="mini-kpi"><small>Total</small><strong>${state.length}</strong></div><div class="mini-kpi warn"><small>Pendentes</small><strong>${count('Pendente')}</strong></div><div class="mini-kpi"><small>Em rota</small><strong>${count('Em rota')}</strong></div><div class="mini-kpi ok"><small>Entregues</small><strong>${count('Entregue')}</strong></div></div>
<div class="mini-panel"><div class="miniapp-toolbar"><input id="del-q" class="mini-input" placeholder="Pesquisar NF, cliente ou cidade" value="${esc(q)}"><select id="del-f" class="mini-select">${['Todos','Pendente','Em rota','Entregue'].map(x=>`<option ${x===filter?'selected':''}>${x}</option>`).join('')}</select></div></div>
<div class="mini-table-wrap" style="margin-top:12px"><table class="mini-table"><thead><tr><th>NF</th><th>Cliente</th><th>Cidade</th><th>Rota</th><th>Status</th><th></th></tr></thead><tbody>${list.map(x=>`<tr><td><strong>${x.nf}</strong></td><td>${esc(x.client)}</td><td>${esc(x.city)}</td><td>${esc(x.route)}</td><td><span class="mini-status ${statusClass(x.status)}">${x.status}</span></td><td><button class="mini-btn" data-open="${x.id}">Abrir</button></td></tr>`).join('')}</tbody></table></div>${openId?detail():''}</div></div>`;bind()};
const detail=()=>{const x=state.find(a=>a.id===openId);return `<div class="mini-panel" style="margin-top:12px"><div class="miniapp-top"><div><strong>NF ${x.nf} · ${esc(x.client)}</strong><div class="miniapp-muted">${x.city} · ${x.route}</div></div><button class="mini-btn" data-close-detail>Fechar</button></div><div class="miniapp-actions"><button class="mini-btn ${x.gps?'primary':''}" data-del-action="gps">${x.gps?'GPS capturado ✓':'Capturar GPS'}</button><button class="mini-btn ${x.status==='Em rota'?'primary':''}" data-del-action="route">Iniciar rota</button><button class="mini-btn ${x.proof?'primary':''}" data-del-action="proof">${x.proof?'Comprovante anexado ✓':'Anexar comprovante'}</button><button class="mini-btn primary" data-del-action="finish">Finalizar entrega</button></div><div style="margin-top:10px"><span class="mini-status ${statusClass(x.status)}">${x.status}</span></div></div>`};
const action=a=>{const x=state.find(v=>v.id===openId);if(!x)return;if(a==='gps'){x.gps=true;causeStep=Math.max(causeStep,2)}if(a==='route'){x.status='Em rota';causeStep=Math.max(causeStep,1)}if(a==='proof'){x.proof=true;causeStep=Math.max(causeStep,3)}if(a==='finish'){if(!x.gps||!x.proof){alert('Capture o GPS e anexe o comprovante antes de finalizar.');return}x.status='Entregue';causeStep=5}render()};
const bind=()=>{document.getElementById('del-q')?.addEventListener('input',e=>{q=e.target.value;render()});document.getElementById('del-f')?.addEventListener('change',e=>{filter=e.target.value;render()});rootRef.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{openId=Number(b.dataset.open);render()}));rootRef.querySelector('[data-close-detail]')?.addEventListener('click',()=>{openId=null;render()});rootRef.querySelectorAll('[data-del-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.delAction)))};
const reset=()=>{guideToken++;state=clone(initial);q='';filter='Todos';openId=null;causeStep=0;guideText='';render()};
const guide=async()=>{reset();const token=++guideToken;openId=1;guideText='Abrindo a NF 45821.';render();await wait(900);if(token!==guideToken)return;guideText='Capturando GPS da entrega.';state[0].gps=true;causeStep=2;render();await wait(900);if(token!==guideToken)return;guideText='Motorista iniciou a rota.';state[0].status='Em rota';causeStep=2;render();await wait(1000);if(token!==guideToken)return;guideText='Comprovante anexado no cliente.';state[0].proof=true;causeStep=3;render();await wait(950);if(token!==guideToken)return;guideText='Finalizando entrega e recalculando indicadores.';state[0].status='Entregue';causeStep=5;render();await wait(1300);if(token!==guideToken)return;guideText='OPERAÇÃO CONCLUÍDA — pendências caíram e entregues aumentaram.';render()};
export async function mount(root){rootRef=root;render();return{reset,guide,cancelGuide(){guideToken++},destroy(){guideToken++;rootRef=null}}}
