import {clone,esc,statusClass} from './shared.js';
const initial=[
{id:1,nf:'45821',client:'Mercado Horizonte',route:'Oeste 01',status:'Pendente',city:'Campo Grande'},
{id:2,nf:'45834',client:'Drogaria Central',route:'Oeste 01',status:'Em rota',city:'Bangu'},
{id:3,nf:'45851',client:'Casa Nova',route:'Sul 03',status:'Entregue',city:'Recreio'},
{id:4,nf:'45872',client:'Rede Mais',route:'Oeste 02',status:'Pendente',city:'Santa Cruz'}
];let state=clone(initial),rootRef=null,q='',filter='Todos',openId=null;
const render=()=>{const root=rootRef;if(!root)return;const list=state.filter(x=>(filter==='Todos'||x.status===filter)&&(!q||[x.nf,x.client,x.city].join(' ').toLowerCase().includes(q.toLowerCase())));const count=s=>state.filter(x=>x.status===s).length;
root.innerHTML=`<div class="miniapp"><div class="miniapp-shell"><div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Sistema de Entregas<small class="miniapp-muted">TMS demonstrativo</small></div></div><span class="mini-status ok">Operação online</span></div>
<div class="mini-kpis"><div class="mini-kpi"><small>Total</small><strong>${state.length}</strong></div><div class="mini-kpi warn"><small>Pendentes</small><strong>${count('Pendente')}</strong></div><div class="mini-kpi"><small>Em rota</small><strong>${count('Em rota')}</strong></div><div class="mini-kpi ok"><small>Entregues</small><strong>${count('Entregue')}</strong></div></div>
<div class="mini-panel"><div class="miniapp-toolbar"><input id="del-q" class="mini-input" placeholder="Pesquisar NF, cliente ou cidade" value="${esc(q)}"><select id="del-f" class="mini-select">${['Todos','Pendente','Em rota','Entregue'].map(x=>`<option ${x===filter?'selected':''}>${x}</option>`).join('')}</select></div></div>
<div class="mini-table-wrap" style="margin-top:12px"><table class="mini-table"><thead><tr><th>NF</th><th>Cliente</th><th>Cidade</th><th>Rota</th><th>Status</th><th></th></tr></thead><tbody>${list.map(x=>`<tr><td><strong>${x.nf}</strong></td><td>${esc(x.client)}</td><td>${esc(x.city)}</td><td>${esc(x.route)}</td><td><span class="mini-status ${statusClass(x.status)}">${x.status}</span></td><td><button class="mini-btn" data-open="${x.id}">Abrir</button></td></tr>`).join('')}</tbody></table></div>
${openId?detail():''}</div></div>`;bind()};
const detail=()=>{const x=state.find(a=>a.id===openId);return `<div class="mini-panel" style="margin-top:12px"><div class="miniapp-top"><div><strong>NF ${x.nf} · ${esc(x.client)}</strong><div class="miniapp-muted">${x.city} · ${x.route}</div></div><button class="mini-btn" data-close-detail>Fechar</button></div><div class="mini-form"><label>Status<select class="mini-select" id="del-status">${['Pendente','Em rota','Entregue'].map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></label><label>Observação<input class="mini-input" value="Entrega demonstrativa sem ocorrência"></label></div><p class="miniapp-muted">Ao mudar o status, os KPIs acima são recalculados imediatamente.</p></div>`};
const bind=()=>{document.getElementById('del-q')?.addEventListener('input',e=>{q=e.target.value;render()});document.getElementById('del-f')?.addEventListener('change',e=>{filter=e.target.value;render()});rootRef.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>{openId=Number(b.dataset.open);render()}));rootRef.querySelector('[data-close-detail]')?.addEventListener('click',()=>{openId=null;render()});document.getElementById('del-status')?.addEventListener('change',e=>{state.find(x=>x.id===openId).status=e.target.value;render()})};
export async function mount(root){rootRef=root;render();return{reset(){state=clone(initial);q='';filter='Todos';openId=null;render()},destroy(){rootRef=null}}}
