import {clone,esc,statusClass,wait} from './shared.js?v=20260922-showroom3';
const initial=[
{id:1,nf:'45821',client:'Mercado Horizonte',address:'Campo Grande — RJ',status:'Pendente',gps:false,proof:false},
{id:2,nf:'45834',client:'Drogaria Central',address:'Bangu — RJ',status:'Pendente',gps:false,proof:false},
{id:3,nf:'45851',client:'Casa Nova',address:'Recreio — RJ',status:'Pendente',gps:false,proof:false},
{id:4,nf:'45872',client:'Rede Mais',address:'Santa Cruz — RJ',status:'Pendente',gps:false,proof:false},
{id:5,nf:'45880',client:'Loja Oeste',address:'Realengo — RJ',status:'Pendente',gps:false,proof:false},
{id:6,nf:'45891',client:'Mercado Sul',address:'Jacarepaguá — RJ',status:'Pendente',gps:false,proof:false},
{id:7,nf:'45903',client:'Farma Rio',address:'Taquara — RJ',status:'Pendente',gps:false,proof:false},
{id:8,nf:'45915',client:'Casa Center',address:'Paciência — RJ',status:'Pendente',gps:false,proof:false}
];let state=clone(initial),rootRef=null,open=null,guideText='',guideToken=0,arrival=false;
const firstDone=()=>state[0].status==='Entregue';
const render=()=>{const current=open?state.find(x=>x.id===open):null;rootRef.innerHTML=`<div class="miniapp">${guideText?'<div class="demo-guide-banner"><strong>DEMONSTRAÇÃO GUIADA</strong><span>'+esc(guideText)+'</span></div>':''}<div class="demo-challenge ${firstDone()?'completed':''}" style="max-width:390px;margin:0 auto 12px"><small>DESAFIO</small><strong>${firstDone()?'✓ DESAFIO CONCLUÍDO':'Finalize a NF 45821.'}</strong><p>${firstDone()?'A entrega foi concluída e agora restam 7 entregas.':'Inicie rota, capture GPS, registre chegada, anexe comprovante e finalize.'}</p></div><div class="mini-mobile"><div class="mini-mobile-head"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Olá, Carlos<small style="display:block;color:#93a3b8;font-size:9px">8 entregas hoje · Rota Oeste 01</small></div></div></div><div class="mini-mobile-body">${current?detail(current):list()}</div></div></div>`;bind()};
const list=()=>`<div class="miniapp-top"><div><strong>Minhas entregas</strong><div class="miniapp-muted">${state.filter(x=>x.status!=='Entregue').length} entregas restantes</div></div><span class="mini-status ok">Online</span></div>${state.map(x=>`<button class="mini-panel" data-open-driver="${x.id}" style="width:100%;text-align:left;margin-bottom:9px"><div class="route-line" style="padding:0;border:0"><span class="route-num">${x.id}</span><div><strong>NF ${x.nf} · ${esc(x.client)}</strong><div class="miniapp-muted">${esc(x.address)}</div></div><span class="mini-status ${statusClass(x.status)}">${x.status}</span></div></button>`).join('')}`;
const detail=x=>`<button class="mini-btn" data-back-driver>← Minhas entregas</button><div style="margin:16px 0"><small class="miniapp-muted">PRÓXIMA ENTREGA</small><strong style="display:block;margin-top:5px">NF ${x.nf}</strong><h3 style="margin:5px 0">${esc(x.client)}</h3><p class="miniapp-muted">${esc(x.address)}</p></div><div class="mini-panel"><span class="mini-status ${statusClass(x.status)}">${x.status}</span><div style="margin-top:14px;display:grid;gap:8px">${x.status==='Pendente'?'<button class="mini-btn primary" data-driver-action="start">INICIAR ROTA</button>':''}${x.status==='Em rota'&&!x.gps?'<button class="mini-btn primary" data-driver-action="gps">CAPTURAR GPS</button>':''}${x.gps&&!arrival?'<button class="mini-btn" data-driver-action="arrival">REGISTRAR CHEGADA</button>':''}${arrival&&!x.proof?'<button class="mini-btn primary" data-driver-action="proof">ANEXAR COMPROVANTE</button>':''}${x.proof&&x.status!=='Entregue'?'<button class="mini-btn primary" data-driver-action="finish">FINALIZAR ENTREGA</button>':''}${x.status==='Entregue'?'<div class="mini-status ok">ENTREGA CONCLUÍDA ✓</div>':''}</div>${x.gps?'<div class="miniapp-muted" style="margin-top:9px">GPS capturado ✓</div>':''}${arrival?'<div class="miniapp-muted">Chegada ao cliente ✓</div>':''}${x.proof?'<div class="miniapp-muted">Comprovante anexado ✓</div>':''}</div>`;
const action=a=>{const x=state.find(v=>v.id===open);if(a==='start')x.status='Em rota';if(a==='gps')x.gps=true;if(a==='arrival')arrival=true;if(a==='proof')x.proof=true;if(a==='finish'){if(!x.gps||!x.proof||!arrival)return;x.status='Entregue'}render()};
const bind=()=>{rootRef.querySelectorAll('[data-open-driver]').forEach(b=>b.addEventListener('click',()=>{open=Number(b.dataset.openDriver);arrival=false;render()}));rootRef.querySelector('[data-back-driver]')?.addEventListener('click',()=>{open=null;arrival=false;render()});rootRef.querySelectorAll('[data-driver-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.driverAction)))};
const reset=()=>{guideToken++;state=clone(initial);open=null;arrival=false;guideText='';render()};
const guide=async()=>{reset();const token=++guideToken;open=1;guideText='Abrindo a próxima entrega: NF 45821.';render();await wait(850);if(token!==guideToken)return;state[0].status='Em rota';guideText='Rota iniciada.';render();await wait(850);if(token!==guideToken)return;state[0].gps=true;guideText='GPS capturado.';render();await wait(850);if(token!==guideToken)return;arrival=true;guideText='Chegada ao cliente registrada.';render();await wait(850);if(token!==guideToken)return;state[0].proof=true;guideText='Comprovante anexado.';render();await wait(850);if(token!==guideToken)return;state[0].status='Entregue';guideText='ENTREGA CONCLUÍDA ✓ · 7 entregas restantes.';render()};
export async function mount(root){rootRef=root;render();return{reset,guide,cancelGuide(){guideToken++},destroy(){guideToken++;rootRef=null}}}
