import {clone,esc,uid,money,statusClass} from './shared.js';
const initial={
clients:[{id:'CLI-001',name:'Mercado Horizonte',city:'Campo Grande',status:'Ativo'},{id:'CLI-002',name:'Drogaria Central',city:'Bangu',status:'Ativo'}],
products:[{id:'PRD-101',name:'Caixa reforçada',stock:36,price:18.9},{id:'PRD-102',name:'Filme stretch',stock:12,price:42.5}],
orders:[{id:'PED-2301',client:'Mercado Horizonte',value:1860,status:'Separação'},{id:'PED-2302',client:'Drogaria Central',value:940,status:'Expedido'}],
deliveries:[{id:'ENT-701',client:'Mercado Horizonte',status:'Em rota'},{id:'ENT-702',client:'Drogaria Central',status:'Pendente'}]
};
let state=clone(initial),rootRef=null,tab='Dashboard',edit=null;
const tabs=['Dashboard','Clientes','Produtos','Estoque','Pedidos','Entregas'];
const render=()=>{if(!rootRef)return;rootRef.innerHTML=`<div class="miniapp"><div class="miniapp-shell"><div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>ERP Operacional<small class="miniapp-muted">Ambiente demonstrativo integrado</small></div></div><span class="mini-status ok">Sessão fictícia</span></div><div class="mini-tabs">${tabs.map(x=>`<button class="mini-tab ${x===tab?'active':''}" data-tab="${x}">${x}</button>`).join('')}</div><div id="erp-view">${view()}</div></div></div>`;bind()};
const view=()=>{if(tab==='Dashboard')return dashboard();if(tab==='Clientes')return clients();if(tab==='Produtos')return products();if(tab==='Estoque')return stock();if(tab==='Pedidos')return orders();return deliveries()};
const dashboard=()=>`<div class="mini-kpis"><div class="mini-kpi"><small>Clientes</small><strong>${state.clients.length}</strong></div><div class="mini-kpi"><small>Produtos</small><strong>${state.products.length}</strong></div><div class="mini-kpi"><small>Pedidos</small><strong>${state.orders.length}</strong></div><div class="mini-kpi ok"><small>Faturamento simulado</small><strong>${money(state.orders.reduce((a,x)=>a+x.value,0)).replace(',00','')}</strong></div></div><div class="mini-grid-2"><div class="mini-panel"><strong>Operação</strong><p class="miniapp-muted">Cadastros e alterações feitas nos módulos afetam imediatamente esta visão.</p><table class="mini-table"><tr><td>Estoque total</td><td><strong>${state.products.reduce((a,x)=>a+x.stock,0)}</strong></td></tr><tr><td>Entregas abertas</td><td><strong>${state.deliveries.filter(x=>x.status!=='Entregue').length}</strong></td></tr></table></div><div class="mini-panel"><strong>Últimos pedidos</strong>${state.orders.slice(-3).map(x=>`<div class="route-line"><span class="route-num">${x.id.slice(-2)}</span><div><strong>${esc(x.client)}</strong><div class="miniapp-muted">${x.id}</div></div><span class="mini-status ${statusClass(x.status)}">${x.status}</span></div>`).join('')}</div></div>`;
const clients=()=>`<div class="mini-panel"><div class="miniapp-top"><strong>Clientes</strong><button class="mini-btn primary" data-action="client-new">+ Cadastrar</button></div><div class="mini-table-wrap"><table class="mini-table"><thead><tr><th>ID</th><th>Cliente</th><th>Cidade</th><th>Status</th><th></th></tr></thead><tbody>${state.clients.map(x=>`<tr><td>${x.id}</td><td>${esc(x.name)}</td><td>${esc(x.city)}</td><td><span class="mini-status ${statusClass(x.status)}">${x.status}</span></td><td><button class="mini-btn" data-action="client-edit" data-id="${x.id}">Editar</button> <button class="mini-btn danger" data-action="client-del" data-id="${x.id}">Excluir</button></td></tr>`).join('')}</tbody></table></div>${edit?.type==='client'?formClient():''}</div>`;
const formClient=()=>{const x=edit.id?state.clients.find(a=>a.id===edit.id):{id:'',name:'',city:'',status:'Ativo'};return `<form id="erp-client-form" class="mini-form" style="margin-top:12px"><label>ID<input class="mini-input" name="id" value="${esc(x.id)}" ${edit.id?'readonly':''} required></label><label>Cliente<input class="mini-input" name="name" value="${esc(x.name)}" required></label><label>Cidade<input class="mini-input" name="city" value="${esc(x.city)}" required></label><label>Status<select class="mini-select" name="status"><option>Ativo</option><option>Inativo</option></select></label><div class="full miniapp-actions"><button class="mini-btn primary">Salvar</button><button class="mini-btn" type="button" data-action="cancel">Cancelar</button></div></form>`};
const products=()=>`<div class="mini-panel"><div class="miniapp-top"><strong>Produtos</strong><button class="mini-btn primary" data-action="product-new">+ Cadastrar</button></div><div class="mini-table-wrap"><table class="mini-table"><thead><tr><th>ID</th><th>Produto</th><th>Saldo</th><th>Preço</th><th></th></tr></thead><tbody>${state.products.map(x=>`<tr><td>${x.id}</td><td>${esc(x.name)}</td><td>${x.stock}</td><td>${money(x.price)}</td><td><button class="mini-btn" data-action="product-edit" data-id="${x.id}">Editar</button> <button class="mini-btn danger" data-action="product-del" data-id="${x.id}">Excluir</button></td></tr>`).join('')}</tbody></table></div>${edit?.type==='product'?formProduct():''}</div>`;
const formProduct=()=>{const x=edit.id?state.products.find(a=>a.id===edit.id):{id:'',name:'',stock:0,price:0};return `<form id="erp-product-form" class="mini-form" style="margin-top:12px"><label>ID<input class="mini-input" name="id" value="${esc(x.id)}" ${edit.id?'readonly':''} required></label><label>Produto<input class="mini-input" name="name" value="${esc(x.name)}" required></label><label>Saldo<input class="mini-input" type="number" min="0" name="stock" value="${x.stock}" required></label><label>Preço<input class="mini-input" type="number" min="0" step=".01" name="price" value="${x.price}" required></label><div class="full miniapp-actions"><button class="mini-btn primary">Salvar</button><button class="mini-btn" type="button" data-action="cancel">Cancelar</button></div></form>`};
const stock=()=>`<div class="mini-panel"><strong>Estoque integrado</strong><p class="miniapp-muted">Edite o saldo em Produtos e esta visão será atualizada.</p>${state.products.map(x=>`<div class="route-line"><span class="route-num">${x.stock}</span><div><strong>${esc(x.name)}</strong><div class="miniapp-muted">${x.id}</div></div><span class="mini-status ${x.stock<15?'warn':'ok'}">${x.stock<15?'Atenção':'Normal'}</span></div>`).join('')}</div>`;
const orders=()=>`<div class="mini-panel"><div class="miniapp-top"><strong>Pedidos</strong><button class="mini-btn primary" data-action="order-new">+ Novo pedido</button></div><div class="mini-table-wrap"><table class="mini-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Valor</th><th>Status</th></tr></thead><tbody>${state.orders.map(x=>`<tr><td>${x.id}</td><td>${esc(x.client)}</td><td>${money(x.value)}</td><td><select class="mini-select" data-order-status="${x.id}">${['Aberto','Separação','Expedido'].map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>${edit?.type==='order'?formOrder():''}</div>`;
const formOrder=()=>`<form id="erp-order-form" class="mini-form" style="margin-top:12px"><label>Cliente<select class="mini-select" name="client">${state.clients.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select></label><label>Valor<input class="mini-input" type="number" min="0" name="value" value="500" required></label><div class="full miniapp-actions"><button class="mini-btn primary">Salvar</button><button class="mini-btn" type="button" data-action="cancel">Cancelar</button></div></form>`;
const deliveries=()=>`<div class="mini-panel"><strong>Entregas</strong>${state.deliveries.map(x=>`<div class="route-line"><span class="route-num">${x.id.slice(-2)}</span><div><strong>${esc(x.client)}</strong><div class="miniapp-muted">${x.id}</div></div><select class="mini-select" data-del-status="${x.id}">${['Pendente','Em rota','Entregue'].map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></div>`).join('')}</div>`;
const bind=()=>{rootRef.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;edit=null;render()}));rootRef.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action,b.dataset.id)));
 rootRef.querySelectorAll('[data-order-status]').forEach(s=>s.addEventListener('change',()=>{state.orders.find(x=>x.id===s.dataset.orderStatus).status=s.value;render()}));
 rootRef.querySelectorAll('[data-del-status]').forEach(s=>s.addEventListener('change',()=>{state.deliveries.find(x=>x.id===s.dataset.delStatus).status=s.value;render()}));
 document.getElementById('erp-client-form')?.addEventListener('submit',saveClient);document.getElementById('erp-product-form')?.addEventListener('submit',saveProduct);document.getElementById('erp-order-form')?.addEventListener('submit',saveOrder)};
const action=(a,id)=>{if(a==='cancel')edit=null;if(a==='client-new')edit={type:'client'};if(a==='client-edit')edit={type:'client',id};if(a==='client-del')state.clients=state.clients.filter(x=>x.id!==id);if(a==='product-new')edit={type:'product'};if(a==='product-edit')edit={type:'product',id};if(a==='product-del')state.products=state.products.filter(x=>x.id!==id);if(a==='order-new')edit={type:'order'};render()};
const saveClient=e=>{e.preventDefault();const f=new FormData(e.target);const obj={id:String(f.get('id')||uid('CLI')),name:String(f.get('name')),city:String(f.get('city')),status:String(f.get('status'))};if(edit.id)Object.assign(state.clients.find(x=>x.id===edit.id),obj);else state.clients.push(obj);edit=null;render()};
const saveProduct=e=>{e.preventDefault();const f=new FormData(e.target);const obj={id:String(f.get('id')||uid('PRD')),name:String(f.get('name')),stock:Number(f.get('stock')),price:Number(f.get('price'))};if(edit.id)Object.assign(state.products.find(x=>x.id===edit.id),obj);else state.products.push(obj);edit=null;render()};
const saveOrder=e=>{e.preventDefault();const f=new FormData(e.target);state.orders.push({id:uid('PED'),client:String(f.get('client')),value:Number(f.get('value')),status:'Aberto'});edit=null;render()};
export async function mount(root){rootRef=root;render();return{reset(){state=clone(initial);tab='Dashboard';edit=null;render()},destroy(){rootRef=null}}}
