import {wait,esc} from './shared.js';
const steps=['Google Sheets','Automação','Web App','ERP','Dashboard','Notificação'];let rootRef=null,active=-1,running=false,guideText='',guideToken=0,startedAt=0,elapsed='—';
const done=()=>active>=steps.length;
const render=()=>{if(!rootRef)return;rootRef.innerHTML=`<div class="miniapp"><div class="miniapp-shell">${guideText?'<div class="demo-guide-banner"><strong>DEMONSTRAÇÃO GUIADA</strong><span>'+esc(guideText)+'</span></div>':''}<div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Integrações<small class="miniapp-muted">O dado viaja de sistema para sistema</small></div></div><button class="mini-btn primary" id="int-run" ${running?'disabled':''}>${running?'Fluxo em execução…':'Executar fluxo'}</button></div>
<div class="demo-challenge ${done()?'completed':''}"><small>DESAFIO</small><strong>${done()?'✓ DESAFIO CONCLUÍDO':'Execute o fluxo PED-8841 de ponta a ponta.'}</strong><p>${done()?'Todos os sistemas receberam o mesmo pacote de dados.':'Acompanhe o pacote PED-8841 · 8 volumes passando por cada etapa.'}</p></div>
<div class="mini-panel"><div class="integration-live-track"><div class="integration-packet" style="--packet-left:${8+Math.max(0,Math.min(active,5))*16.8}%"><strong>PED-8841</strong><span>8 volumes</span></div>${steps.map((s,i)=>`<div class="integration-stop ${i<active||done()?'done':i===active?'active':''}"><b>${s}</b><span>${i<active||done()?'✓':i===active?'recebendo…':'aguardando'}</span></div>`).join('')}</div></div>
<div class="mini-grid-2" style="margin-top:12px"><div class="mini-panel"><strong>Payload fictício</strong><pre class="mini-log" style="height:220px">{
  "pedido": "PED-8841",
  "cliente": "Mercado Horizonte",
  "volumes": 8,
  "status": "${done()?'processo_concluido':active<1?'recebido':active<3?'validado':'sincronizado'}"
}</pre></div><div class="mini-panel"><strong>Resultado do fluxo</strong><div style="margin-top:12px">${steps.map((s,i)=>`<div class="route-line"><span class="route-num">${i+1}</span><div><strong>${s}</strong><div class="miniapp-muted">${i<active||done()?'Concluído':i===active?'Processando…':'Aguardando'}</div></div><span class="mini-status ${i<active||done()?'ok':i===active?'blue':''}">${i<active||done()?'OK':i===active?'LIVE':'—'}</span></div>`).join('')}</div>${done()?'<div class="demo-complete" style="margin-top:12px"><strong>PROCESSO CONCLUÍDO</strong><p>'+elapsed+' · pacote sincronizado ponta a ponta</p></div>':''}</div></div></div></div>`;document.getElementById('int-run')?.addEventListener('click',()=>run(false))};
const run=async(fromGuide=false)=>{if(running)return;running=true;active=0;startedAt=performance.now();const token=++guideToken;render();for(let i=0;i<steps.length;i++){if(token!==guideToken)return;active=i;if(fromGuide)guideText='PED-8841 entrando em '+steps[i]+'.';render();await wait(650)}if(token!==guideToken)return;active=steps.length;running=false;elapsed=((performance.now()-startedAt)/1000).toFixed(1).replace('.',',')+' s';if(fromGuide)guideText='Todos os sistemas confirmaram o mesmo dado.';render()};
const reset=()=>{guideToken++;active=-1;running=false;guideText='';elapsed='—';render()};
const guide=async()=>{reset();guideText='Um pacote realista nasce no Google Sheets e será sincronizado ponta a ponta.';render();await wait(800);return run(true)};
export async function mount(root){rootRef=root;render();return{reset,guide,cancelGuide(){guideToken++;running=false},destroy(){guideToken++;rootRef=null}}}
