const steps=['Google Sheets','Automação','Web App','ERP','Dashboard','Notificação'];let rootRef=null,active=-1,running=false,timers=[];
const render=()=>{rootRef.innerHTML=`<div class="miniapp"><div class="miniapp-shell"><div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Integrações<small class="miniapp-muted">Fluxo ponta a ponta demonstrativo</small></div></div><button class="mini-btn primary" id="int-run" ${running?'disabled':''}>${running?'Fluxo em execução…':'Executar fluxo'}</button></div><div class="mini-panel"><div class="flow-track">${steps.map((s,i)=>`<div class="flow-node ${i<active?'done':i===active?'active':''}"><span>0${i+1}</span><br>${s}</div>`).join('')}</div></div><div class="mini-grid-2" style="margin-top:12px"><div class="mini-panel"><strong>Payload fictício</strong><pre class="mini-log" style="height:220px">{
  "pedido": "PED-8841",
  "cliente": "Mercado Horizonte",
  "volumes": 8,
  "status": "${active<0?'recebido':active<2?'validado':active<4?'sincronizado':'processado'}"
}</pre></div><div class="mini-panel"><strong>Resultado do fluxo</strong><div style="margin-top:12px">${steps.map((s,i)=>`<div class="route-line"><span class="route-num">${i+1}</span><div><strong>${s}</strong><div class="miniapp-muted">${i<active?'Concluído':i===active?'Processando…':'Aguardando'}</div></div><span class="mini-status ${i<active?'ok':i===active?'blue':''}">${i<active?'OK':i===active?'LIVE':'—'}</span></div>`).join('')}</div></div></div></div></div>`;document.getElementById('int-run')?.addEventListener('click',run)};
const run=()=>{if(running)return;running=true;active=-1;render();steps.forEach((_,i)=>timers.push(setTimeout(()=>{active=i;render();if(i===steps.length-1){timers.push(setTimeout(()=>{running=false;active=steps.length;render()},650))}},520*(i+1))))};
export async function mount(root){rootRef=root;render();return{reset(){timers.forEach(clearTimeout);timers=[];running=false;active=-1;render()},destroy(){timers.forEach(clearTimeout);rootRef=null}}}
