import {clone,esc,wait} from './shared.js?v=20260922-showroom3';
const initial={drivers:[{id:'M01',name:'Carlos Souza',route:'Oeste 01'},{id:'M02',name:'Marcos Lima',route:'Zona Sul 02'}],routes:{
'Oeste 01':[{seq:1,nf:'45821',client:'Mercado Horizonte',city:'Bangu',km:6.8,status:'Pendente'},{seq:2,nf:'45834',client:'Drogaria Central',city:'Campo Grande',km:11.4,status:'Pendente'},{seq:3,nf:'45842',client:'Casa Popular',city:'Santa Cruz',km:14.2,status:'Pendente'}],
'Zona Sul 02':[{seq:1,nf:'45901',client:'Loja Atlântico',city:'Botafogo',km:4.1,status:'Em rota'},{seq:2,nf:'45911',client:'Mercado Praia',city:'Copacabana',km:5.7,status:'Pendente'}]
}};let state=clone(initial),rootRef=null,driver='M01',guideText='',guideToken=0;
const done=()=>state.routes['Oeste 01'][0].status==='Entregue';
const render=()=>{const d=state.drivers.find(x=>x.id===driver),list=state.routes[d.route],km=list.reduce((a,x)=>a+x.km,0);rootRef.innerHTML=`<div class="miniapp"><div class="miniapp-shell">${guideText?'<div class="demo-guide-banner"><strong>DEMONSTRAÇÃO GUIADA</strong><span>'+esc(guideText)+'</span></div>':''}<div class="miniapp-top"><div class="miniapp-brand"><span class="miniapp-mark">V/</span><div>Roteirizador<small class="miniapp-muted">Planejamento operacional fictício</small></div></div><select class="mini-select" id="route-driver">${state.drivers.map(x=>`<option value="${x.id}" ${x.id===driver?'selected':''}>${esc(x.name)} · ${x.route}</option>`).join('')}</select></div><div class="demo-challenge ${done()?'completed':''}"><small>DESAFIO</small><strong>${done()?'✓ DESAFIO CONCLUÍDO':'Conclua a primeira parada da rota Oeste 01.'}</strong><p>Altere o status da NF 45821 de Pendente → Em rota → Entregue.</p></div><div class="mini-kpis"><div class="mini-kpi"><small>Paradas</small><strong>${list.length}</strong></div><div class="mini-kpi"><small>Distância</small><strong>${km.toFixed(1)} km</strong></div><div class="mini-kpi"><small>Em rota</small><strong>${list.filter(x=>x.status==='Em rota').length}</strong></div><div class="mini-kpi ok"><small>Concluídas</small><strong>${list.filter(x=>x.status==='Entregue').length}</strong></div></div><div class="mini-grid-2"><div class="mini-panel"><strong>Sequência de entregas</strong><div style="margin-top:8px">${list.map(x=>`<div class="route-line"><span class="route-num">${String(x.seq).padStart(2,'0')}</span><div><strong>NF ${x.nf} · ${esc(x.client)}</strong><div class="miniapp-muted">${esc(x.city)} · ${x.km} km</div></div><button class="mini-btn" data-route-status="${x.nf}">${x.status}</button></div>`).join('')}</div></div><div class="mini-panel"><strong>Mapa operacional simplificado</strong><div class="route-map-demo">${list.map((x,i)=>`<span class="${x.status==='Entregue'?'done':x.status==='Em rota'?'active':''}" style="left:${16+i*27}%;top:${24+(i%2)*32}%">${x.seq}</span>`).join('')}<i></i></div></div></div></div></div>`;bind()};
const cycle=x=>{x.status=x.status==='Pendente'?'Em rota':x.status==='Em rota'?'Entregue':'Pendente';render()};
const bind=()=>{document.getElementById('route-driver')?.addEventListener('change',e=>{driver=e.target.value;render()});rootRef.querySelectorAll('[data-route-status]').forEach(b=>b.addEventListener('click',()=>{const d=state.drivers.find(x=>x.id===driver),x=state.routes[d.route].find(y=>y.nf===b.dataset.routeStatus);cycle(x)}))};
const reset=()=>{guideToken++;state=clone(initial);driver='M01';guideText='';render()};
const guide=async()=>{reset();const token=++guideToken;guideText='Selecionando Carlos Souza · Rota Oeste 01.';render();await wait(900);if(token!==guideToken)return;state.routes['Oeste 01'][0].status='Em rota';guideText='NF 45821 saiu para entrega.';render();await wait(1100);if(token!==guideToken)return;state.routes['Oeste 01'][0].status='Entregue';guideText='Primeira parada concluída; indicadores e mapa atualizados.';render()};
export async function mount(root){rootRef=root;render();return{reset,guide,cancelGuide(){guideToken++},destroy(){guideToken++;rootRef=null}}}
